# baseURL = "https://mystifying-yalow-8b46ef.netlify.app"
baseURL = "https://deploy-preview-1--mystifying-yalow-8b46ef.netlify.app"
languageCode = "en-us"
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
copyrighthtml = "&copy; 2022 Internet Security Research Group. All rights reserved."
address = "548 Market St, PMB 57274, San Francisco, California 94104-5401"
address_line_1 = "548 Market St, PMB 57274"
address_line_2 = "San Francisco, California 94104-5401"
images = ["images/DivviUpSocialShare.png"]
meta_description = "@todo"

# Date and time formatting, see https://gohugo.io/functions/format/
time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
time_format_RFC822 = "Mon, 02 Jan 2006 15:04:05 -0700"
time_format_default = "Jan 2, 2006"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark]
[markup.goldmark.extensions]
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
# To keep ยง ids identical after the migration from blackfriday to goldmark
autoHeadingIDType = "blackfriday"

[languages]
[languages.en]
title = "Divvi Up"
languageName ="English"
# Weight used for sorting.
weight = 1
description = "@todo"
